### Save Owner
POST http://localhost:8080/owners

### Find Owner
GET http://localhost:8080/owners

### Update Owner
PUT http://localhost:8080/owners

### Update Pet Details
PATCH http://localhost:8080/owners

### Delete Owner
DELETE http://localhost:8080/owners

### Find All Owners
GET http://localhost:8080/owners/all

